[project]
name = "myproject"

...

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.30.0"
urllib3 = "<2"

...

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"